import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { ContentStatus, Prisma, StaffRole } from '@prisma/client'; import { randomUUID } from 'node:crypto';
import { Principal } from '../common/principal'; import { TenantAccessService } from '../common/tenant-access.service'; import { PrismaService } from '../database/prisma.service'; import { StorageService } from '../providers/storage.service'; import { BlogDto, CmsPageDto, CreateMediaDto, DeviceTokenDto, DispatchNotificationDto, ReportRequestDto, TemplateDto } from './platform.dto';
@Injectable() export class PlatformService {
  constructor(private readonly prisma: PrismaService, private readonly access: TenantAccessService, private readonly storage: StorageService) {}
  async media(schoolId: string, dto: CreateMediaDto, user: Principal) { this.access.assertSchool(user, schoolId); const key = `schools/${schoolId}/${randomUUID()}-${dto.fileName.replace(/[^A-Za-z0-9._-]/g, '_')}`; const asset = await this.prisma.mediaAsset.create({ data: { schoolId, storageKey: key, fileName: dto.fileName, mimeType: dto.mimeType, sizeBytes: dto.sizeBytes, checksum: dto.checksum, uploadedById: user.sub } }); return { asset, uploadUrl: await this.storage.uploadUrl(key, dto.mimeType) }; }
  async page(dto: CmsPageDto) { return this.prisma.cmsPage.upsert({ where: { slug: dto.slug }, create: { slug: dto.slug, title: dto.title, sections: dto.sections as Prisma.InputJsonValue, seo: dto.seo as Prisma.InputJsonValue | undefined, status: dto.status, publishedAt: dto.status === ContentStatus.PUBLISHED ? new Date() : undefined }, update: { title: dto.title, sections: dto.sections as Prisma.InputJsonValue, seo: dto.seo as Prisma.InputJsonValue | undefined, status: dto.status, publishedAt: dto.status === ContentStatus.PUBLISHED ? new Date() : undefined } }); }
  async blog(dto: BlogDto, user: Principal) { return this.prisma.blogPost.upsert({ where: { slug: dto.slug }, create: { ...dto, content: dto.content as Prisma.InputJsonValue, seo: dto.seo as Prisma.InputJsonValue | undefined, authorUserId: user.sub, publishedAt: dto.status === ContentStatus.PUBLISHED ? new Date() : undefined }, update: { title: dto.title, excerpt: dto.excerpt, content: dto.content as Prisma.InputJsonValue, category: dto.category, seo: dto.seo as Prisma.InputJsonValue | undefined, status: dto.status, publishedAt: dto.status === ContentStatus.PUBLISHED ? new Date() : undefined } }); }
  publicPage(slug: string) { return this.prisma.cmsPage.findFirstOrThrow({ where: { slug, status: ContentStatus.PUBLISHED } }); }
  publicPosts() { return this.prisma.blogPost.findMany({ where: { status: ContentStatus.PUBLISHED, publishedAt: { lte: new Date() } }, orderBy: { publishedAt: 'desc' }, select: { slug: true, title: true, excerpt: true, featuredImage: true, category: true, publishedAt: true } }); }
  publicPost(slug: string) { return this.prisma.blogPost.findFirstOrThrow({ where: { slug, status: ContentStatus.PUBLISHED } }); }
  template(dto: TemplateDto) { return this.prisma.messageTemplate.upsert({ where: { key_channel: { key: dto.key, channel: dto.channel } }, create: { ...dto, variables: dto.variables as Prisma.InputJsonValue | undefined }, update: { subject: dto.subject, body: dto.body, variables: dto.variables as Prisma.InputJsonValue | undefined, active: true } }); }
  async device(dto: DeviceTokenDto, user: Principal) { if (user.kind !== 'student') throw new ForbiddenException(); return this.prisma.devicePushToken.upsert({ where: { token: dto.token }, create: { schoolId: user.schoolId, studentId: user.sub, ...dto }, update: { schoolId: user.schoolId, studentId: user.sub, platform: dto.platform, deviceId: dto.deviceId, revokedAt: null } }); }
  async notifications(user: Principal) { return this.prisma.notification.findMany({ where: user.kind === 'staff' ? { userId: user.sub } : { studentId: user.sub, schoolId: user.schoolId }, orderBy: { createdAt: 'desc' }, take: 100 }); }
  async readNotification(id: string, user: Principal) { const result = await this.prisma.notification.updateMany({ where: { id, ...(user.kind === 'staff' ? { userId: user.sub } : { studentId: user.sub, schoolId: user.schoolId }) }, data: { status: 'READ' } }); if (!result.count) throw new NotFoundException('Notification not found'); return { success: true }; }
  async dispatch(dto: DispatchNotificationDto) { if (!!dto.userId === !!dto.studentId) throw new ForbiddenException('Exactly one recipient is required'); const template = await this.prisma.messageTemplate.findFirst({ where: { key: dto.templateKey, active: true } }); if (!template) throw new NotFoundException('Template not found'); const allowed = new Set(Array.isArray(template.variables) ? template.variables.filter((value): value is string => typeof value === 'string') : []); const render = (source: string) => source.replace(/{{\s*([A-Za-z0-9_]+)\s*}}/g, (_match, key: string) => allowed.has(key) ? dto.variables[key] ?? '' : ''); return this.prisma.$transaction(async (tx) => { const notification = await tx.notification.create({ data: { schoolId: dto.schoolId, userId: dto.userId, studentId: dto.studentId, channel: template.channel, type: dto.templateKey, title: render(template.subject ?? dto.templateKey), body: render(template.body), payload: dto.variables } }); await tx.backgroundJob.create({ data: { schoolId: dto.schoolId, queue: 'notifications', type: 'SEND_NOTIFICATION', idempotencyKey: `notification:${notification.id}`, payload: { notificationId: notification.id } } }); return notification; }); }
  async report(schoolId: string, dto: ReportRequestDto, user: Principal) { this.access.assertSchool(user, schoolId); const enrollment = await this.prisma.enrollment.findFirst({ where: { schoolId, runId: dto.runId, studentId: dto.studentId } }); if (!enrollment) throw new NotFoundException('Enrollment not found'); const latest = await this.prisma.studentReport.findFirst({ where: { schoolId, runId: dto.runId, studentId: dto.studentId, type: dto.type ?? 'FINAL' }, orderBy: { version: 'desc' } }); return this.prisma.$transaction(async (tx) => { const report = await tx.studentReport.create({ data: { schoolId, runId: dto.runId, studentId: dto.studentId, type: dto.type ?? 'FINAL', version: (latest?.version ?? 0) + 1 } }); await tx.backgroundJob.create({ data: { schoolId, queue: 'reports', type: 'GENERATE_STUDENT_REPORT', idempotencyKey: `report:${report.id}`, payload: { reportId: report.id } } }); await tx.auditLog.create({ data: { schoolId, actorUserId: user.sub, action: 'REPORT_REQUESTED', entityType: 'StudentReport', entityId: report.id } }); return report; }); }
  async reports(schoolId: string, user: Principal) { this.access.assertSchool(user, schoolId); return this.prisma.studentReport.findMany({ where: { schoolId }, orderBy: { createdAt: 'desc' }, take: 100 }); }
  async reportDownload(schoolId: string, reportId: string, user: Principal) { this.access.assertSchool(user, schoolId); const report = await this.prisma.studentReport.findFirst({ where: { id: reportId, schoolId, status: { in: ['READY', 'SENT'] } } }); if (!report?.pdfKey) throw new NotFoundException('Report is not ready'); return { pdfUrl: await this.storage.downloadUrl(report.pdfKey), htmlUrl: report.htmlKey ? await this.storage.downloadUrl(report.htmlKey) : null, expiresIn: 900 }; }
  async runReport(schoolId: string, runId: string, user: Principal) { this.access.assertSchool(user, schoolId); const run = await this.prisma.programRun.findFirst({ where: { id: runId, schoolId }, include: { enrollments: true, sessions: { include: { attendances: true } } } }); if (!run) throw new NotFoundException('Run not found'); const attendance = run.sessions.flatMap((session) => session.attendances); return { runId, students: run.enrollments.length, sessions: run.sessions.length, averageAttendance: attendance.length ? attendance.reduce((sum, item) => sum + Number(item.attendancePercentage), 0) / attendance.length : 0, completedSessions: run.sessions.filter((session) => session.status === 'COMPLETED').length }; }
  async platformReport(user: Principal) { if (user.kind !== 'staff' || !user.roles.some((r) => r.role === StaffRole.ALIF_SUPER_ADMIN)) throw new ForbiddenException(); const [schools, students, sessions, runs, invoices, payments, leads] = await Promise.all([this.prisma.school.count({ where: { status: 'ACTIVE' } }), this.prisma.student.count({ where: { status: 'ACTIVE' } }), this.prisma.learningSession.count(), this.prisma.programRun.count(), this.prisma.invoice.aggregate({ _sum: { total: true } }), this.prisma.payment.aggregate({ _sum: { amount: true } }), this.prisma.lead.groupBy({ by: ['status'], _count: true })]); return { learning: { schools, students, sessions, runs }, commercial: { invoiced: invoices._sum.total ?? 0, paid: payments._sum.amount ?? 0, leads } }; }
  async audit(schoolId: string | undefined, user: Principal, action?: string) { if (user.kind !== 'staff') throw new ForbiddenException(); const global = user.roles.some((r) => r.role === StaffRole.ALIF_SUPER_ADMIN); if (!global) { if (!schoolId) throw new ForbiddenException(); this.access.assertSchool(user, schoolId); } return this.prisma.auditLog.findMany({ where: { ...(schoolId ? { schoolId } : {}), ...(action ? { action } : {}) }, orderBy: { createdAt: 'desc' }, take: 200 }); }
  jobs(user: Principal) { if (user.kind !== 'staff' || !user.roles.some((r) => r.role === StaffRole.ALIF_SUPER_ADMIN)) throw new ForbiddenException(); return this.prisma.backgroundJob.findMany({ orderBy: { createdAt: 'desc' }, take: 200 }); }
}
