import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { LeadStatus } from '@prisma/client';
import { Principal } from '../common/principal'; import { PrismaService } from '../database/prisma.service'; import { CreateLeadDto, LeadActivityDto, LeadStatusDto } from './crm.dto';
@Injectable() export class CrmService {
  constructor(private readonly prisma: PrismaService) {}
  create(dto: CreateLeadDto) { return this.prisma.lead.create({ data: { ...dto, email: dto.email.toLowerCase() } }); }
  list() { return this.prisma.lead.findMany({ include: { activities: { orderBy: { createdAt: 'desc' } } }, orderBy: { createdAt: 'desc' } }); }
  async status(id: string, dto: LeadStatusDto, actor: Principal) { const lead = await this.prisma.lead.findUnique({ where: { id } }); if (!lead) throw new NotFoundException('Lead not found'); return this.prisma.$transaction(async (tx) => { const result = await tx.lead.update({ where: { id }, data: { status: dto.status } }); await tx.auditLog.create({ data: { actorUserId: actor.sub, action: 'LEAD_STATUS_CHANGED', entityType: 'Lead', entityId: id, before: { status: lead.status }, after: { status: dto.status } } }); return result; }); }
  async activity(id: string, dto: LeadActivityDto) { if (!(await this.prisma.lead.findUnique({ where: { id }, select: { id: true } }))) throw new NotFoundException('Lead not found'); return this.prisma.leadActivity.create({ data: { leadId: id, ...dto } }); }
  async convert(id: string, actor: Principal) { return this.prisma.$transaction(async (tx) => { const lead = await tx.lead.findUnique({ where: { id } }); if (!lead) throw new NotFoundException('Lead not found'); if (lead.status !== LeadStatus.WON) throw new BadRequestException('Only won leads can be converted'); if (lead.convertedSchoolId) throw new BadRequestException('Lead is already converted'); const base = lead.schoolName.replace(/[^A-Za-z0-9]/g, '').toUpperCase().slice(0, 8) || 'SCHOOL'; const code = `${base}-${id.slice(0, 4).toUpperCase()}`; const school = await tx.school.create({ data: { code, name: lead.schoolName } }); await tx.lead.update({ where: { id }, data: { convertedSchoolId: school.id } }); await tx.auditLog.create({ data: { schoolId: school.id, actorUserId: actor.sub, action: 'LEAD_CONVERTED', entityType: 'Lead', entityId: id, metadata: { schoolId: school.id } } }); return school; }); }
}
