import { Injectable, ServiceUnavailableException } from '@nestjs/common'; import { ConfigService } from '@nestjs/config'; import { LiveService } from './live.service';
type RecordingRef = { resourceId: string; sid: string; uid: string };
@Injectable() export class RecordingProviderService { private readonly appId: string; private readonly auth: string; private readonly storageConfig: Record<string, unknown> | null;
  constructor(config: ConfigService, private readonly live: LiveService) { this.appId = config.getOrThrow<string>('AGORA_APP_ID'); const customer = config.getOrThrow<string>('AGORA_CUSTOMER_ID'); const secret = config.getOrThrow<string>('AGORA_CUSTOMER_SECRET'); this.auth = customer && secret ? `Basic ${Buffer.from(`${customer}:${secret}`).toString('base64')}` : ''; const raw = config.getOrThrow<string>('AGORA_RECORDING_STORAGE_CONFIG'); this.storageConfig = raw ? JSON.parse(raw) as Record<string, unknown> : null; }
  private ready() { if (!this.appId || !this.auth || !this.storageConfig) throw new ServiceUnavailableException('Agora Cloud Recording is not configured'); }
  private async request(path: string, body: Record<string, unknown>) { this.ready(); const response = await fetch(`https://api.sd-rtn.com/v1/apps/${this.appId}/cloud_recording${path}`, { method: 'POST', headers: { Authorization: this.auth, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(`Agora recording request failed (${response.status})`); return response.json() as Promise<Record<string, unknown>>; }
  async start(channel: string, uid: number, trainerUid: number): Promise<RecordingRef> { const uidText = String(uid || 1); const acquired = await this.request('/acquire', { cname: channel, uid: uidText, clientRequest: { resourceExpiredHour: 24 } }); const resourceId = String(acquired.resourceId); const token = this.live.token(channel, uid, false, 43_200).token; const started = await this.request(`/resourceid/${resourceId}/mode/mix/start`, { cname: channel, uid: uidText, clientRequest: { token, recordingConfig: { channelType: 0, streamTypes: 2, audioProfile: 1, maxIdleTime: 120, subscribeAudioUids: ['#allstream#'], subscribeVideoUids: [String(trainerUid)] }, storageConfig: this.storageConfig } }); return { resourceId, sid: String(started.sid), uid: uidText }; }
  async stop(channel: string, ref: RecordingRef): Promise<string | null> { const stopped = await this.request(`/resourceid/${ref.resourceId}/sid/${ref.sid}/mode/mix/stop`, { cname: channel, uid: ref.uid, clientRequest: {} }); const fileList = (stopped.serverResponse as { fileList?: Array<{ fileName?: string }> } | undefined)?.fileList; return fileList?.find((file) => file.fileName)?.fileName ?? null; }
}
